version: '{build}'
clone_depth: 1

image:
  - Ubuntu

environment:
  DOCKER_PASSWORD:
     secure: 5thIPcBWPN+Qcha5VkR8Ng== 

branches:
  only:
    - main
    - dev

configuration:
  - Release

init:
  - ps: git config --global core.autocrlf true

build_script:
  - ps: dotnet publish -c $Env:CONFIGURATION -o app --no-self-contained /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG src/Nexus/Nexus.csproj

test_script:
  - ps: dotnet test -c $Env:CONFIGURATION /p:BuildProjectReferences=false

artifacts:
  - path: artifacts/packages/**/*.nupkg

after_test:

# Docker
  - ps: docker build -t apollo3zehn/nexus:1.0.0.alpha.1.$Env:APPVEYOR_BUILD_NUMBER .
  - ps: docker login -u="apollo3zehn" -p="$env:DOCKER_PASSWORD"
  - ps: docker push apollo3zehn/nexus:1.0.0.alpha.1.$Env:APPVEYOR_BUILD_NUMBER

deploy:

# MyGet (dev)
  - provider: NuGet
    server: https://www.myget.org/F/apollo3zehn-dev/api/v2/package
    api_key:
      secure: DVadlPknnKPMR4F2+3VqeU7BFFmtLcXDHzkySA590MqQNIdzbx8HRuaPwDVbHRqX
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      branch: dev

# NuGet (master)
  - provider: NuGet
    server: https://www.nuget.org/api/v2/package
    api_key:
      secure: /+MsVllJKX6M/MHBmCXaBFf1ttNDSqO04J7frGM81UUgBwfDUs6Wn4WufiU0Wl3/
    skip_symbols: true
    artifact: /.*\.nupkg/ 
    on:
      branch: main
      APPVEYOR_REPO_TAG: true