version: '{build}'
clone_depth: 1

image:
  - Ubuntu

environment:
  DOCKER_PASSWORD:
     secure: 5thIPcBWPN+Qcha5VkR8Ng== 

branches:
  only:
    - master
    - dev

configuration:
  - Release

init:
  - git config --global core.autocrlf true

before_build:
  - ps: dotnet --info
  - ps: "Get-ChildItem Env:"

build_script:
 - ps: sudo docker build -t apollo3zehn/nexus:1.0.0.alpha.1.$Env:APPVEYOR_BUILD_NUMBER .

test_script:
 - ps: dotnet test ./tests/Nexus.Tests -c $Env:CONFIGURATION

artifacts:
  - path: ./artifacts/packages/**/*.nupkg

after_test:

# Docker
  - ps: docker login -u="apollo3zehn" -p="$env:DOCKER_PASSWORD"
  - ps: docker push apollo3zehn/nexus:1.0.0.alpha.1.$Env:APPVEYOR_BUILD_NUMBER

deploy:

# MyGet (dev)
  - provider: NuGet
    server: https://www.myget.org/F/apollo3zehn-dev/api/v2/package
    api_key:
      secure: DVadlPknnKPMR4F2+3VqeU7BFFmtLcXDHzkySA590MqQNIdzbx8HRuaPwDVbHRqX
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      branch: dev
      CI_LINUX: true

# NuGet (master)
  - provider: NuGet
    server: https://www.nuget.org/api/v2/package
    api_key:
      secure: /+MsVllJKX6M/MHBmCXaBFf1ttNDSqO04J7frGM81UUgBwfDUs6Wn4WufiU0Wl3/
    skip_symbols: true
    artifact: /.*\.nupkg/ 
    on:
      branch: master
      CI_WINDOWS: true
      APPVEYOR_REPO_TAG: true

# GitHub (master)
  - provider: GitHub
    force_update: true
    auth_token:
      secure: Ssl8rHF6345+qU9lhUQlHRx0Ta4e6UXIQM3SEpDpjR4+WcpMJM3TvQ5gUWjwf6jQ
    artifact: /.*\.msi/
    on:
      CI_WINDOWS: true
      APPVEYOR_REPO_TAG: true