//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexus {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nexus.Types.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The buffer type is invalid. ähnelt.
        /// </summary>
        internal static string ChannelContext_BufferTypeInvalid {
            get {
                return ResourceManager.GetString("ChannelContext_BufferTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The provided type must be assignable to IBuffer. ähnelt.
        /// </summary>
        internal static string ChannelDescription_BufferTypeInvalid {
            get {
                return ResourceManager.GetString("ChannelDescription_BufferTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The MaximumDatasetAge must be between 0 and 10000. ähnelt.
        /// </summary>
        internal static string DataReaderExtensionSettingsBase_MaximumDatasetAgeInvalid {
            get {
                return ResourceManager.GetString("DataReaderExtensionSettingsBase_MaximumDatasetAgeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The requested period has already been written before. ähnelt.
        /// </summary>
        internal static string DataWriterExtensionLogicBase_DateTimeAlreadyWritten {
            get {
                return ResourceManager.GetString("DataWriterExtensionLogicBase_DateTimeAlreadyWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DateTime and TimeSpan arguments must have a granularity &gt;= 1 s. ähnelt.
        /// </summary>
        internal static string DataWriterExtensionLogicBase_DateTimeGranularityTooHigh {
            get {
                return ResourceManager.GetString("DataWriterExtensionLogicBase_DateTimeGranularityTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file granularity is higher than the sample period. ähnelt.
        /// </summary>
        internal static string DataWriterExtensionLogicBase_FileGranularityTooHigh {
            get {
                return ResourceManager.GetString("DataWriterExtensionLogicBase_FileGranularityTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file granularity value is invalid. ähnelt.
        /// </summary>
        internal static string DataWriterExtensionSettingsBase_FileGranularityInvalid {
            get {
                return ResourceManager.GetString("DataWriterExtensionSettingsBase_FileGranularityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ExtensionContextAttribute is not defined. ähnelt.
        /// </summary>
        internal static string ExtensionSettingsBase_ExtensionContextAttributeNotDefined {
            get {
                return ResourceManager.GetString("ExtensionSettingsBase_ExtensionContextAttributeNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ExtensionDescriptionAttribute is not defined. ähnelt.
        /// </summary>
        internal static string ExtensionSettingsBase_ExtensionDescriptionAttributeNotDefined {
            get {
                return ResourceManager.GetString("ExtensionSettingsBase_ExtensionDescriptionAttributeNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One or more channel names are invalid ähnelt.
        /// </summary>
        internal static string NexusProject_ChannelHubNameInvalid {
            get {
                return ResourceManager.GetString("NexusProject_ChannelHubNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The channel set is invalid: A channel must be unique. ähnelt.
        /// </summary>
        internal static string NexusProject_ChannelHubNotUnqiue {
            get {
                return ResourceManager.GetString("NexusProject_ChannelHubNotUnqiue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data gateway settings IDs are not unique. ähnelt.
        /// </summary>
        internal static string NexusProject_DataGatewaySettingsIdNotUnique {
            get {
                return ResourceManager.GetString("NexusProject_DataGatewaySettingsIdNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The data writer settings IDs are not unique. ähnelt.
        /// </summary>
        internal static string NexusProject_DataWriterSettingsIdNotUnique {
            get {
                return ResourceManager.GetString("NexusProject_DataWriterSettingsIdNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The 1st level group name is invalid. ähnelt.
        /// </summary>
        internal static string NexusProject_PrimaryGroupNameInvalid {
            get {
                return ResourceManager.GetString("NexusProject_PrimaryGroupNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The project name is invalid. ähnelt.
        /// </summary>
        internal static string NexusProject_ProjectNameInvalid {
            get {
                return ResourceManager.GetString("NexusProject_ProjectNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The 2nd level group name is invalid. ähnelt.
        /// </summary>
        internal static string NexusProject_SecondaryGroupNameInvalid {
            get {
                return ResourceManager.GetString("NexusProject_SecondaryGroupNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The format version must be equal or greater zero. ähnelt.
        /// </summary>
        internal static string NexusProjectDescription_InvalidFormatVersion {
            get {
                return ResourceManager.GetString("NexusProjectDescription_InvalidFormatVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The project version must be equal or greater zero. ähnelt.
        /// </summary>
        internal static string NexusProjectDescription_InvalidVersion {
            get {
                return ResourceManager.GetString("NexusProjectDescription_InvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use A-Z, a-z, 0-9 or _. ähnelt.
        /// </summary>
        internal static string NexusUtilities_InvalidCharacters {
            get {
                return ResourceManager.GetString("NexusUtilities_InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use A-Z or a-z as first character. ähnelt.
        /// </summary>
        internal static string NexusUtilities_InvalidLeadingCharacter {
            get {
                return ResourceManager.GetString("NexusUtilities_InvalidLeadingCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A project id must start with a &apos;/&apos; as first character. ähnelt.
        /// </summary>
        internal static string NexusUtilities_InvalidLeadingCharacter2 {
            get {
                return ResourceManager.GetString("NexusUtilities_InvalidLeadingCharacter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A project id must contain three &apos;/&apos; path separators. ähnelt.
        /// </summary>
        internal static string NexusUtilities_InvalidPathSeparatorCount {
            get {
                return ResourceManager.GetString("NexusUtilities_InvalidPathSeparatorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name must not be empty. ähnelt.
        /// </summary>
        internal static string NexusUtilities_NameEmpty {
            get {
                return ResourceManager.GetString("NexusUtilities_NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid group identifier. ähnelt.
        /// </summary>
        internal static string ProjectInfo {
            get {
                return ResourceManager.GetString("ProjectInfo", resourceCulture);
            }
        }
    }
}
